### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by NickAzureDevops**
### Checklist

- [x] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)
- [ ] Does this PR introduce a breaking change

### CODE REVIEW

**Review by reespozzi — COMMENTED** [review]
Are you using all of these in helmcharts report?

**Comment by NickAzureDevops** [comment]
> Are you using all of these in helmcharts report?

I have 3 of them i know for sure.

**Comment by NickAzureDevops** [comment]
I am not 100% sure if there are more @reespozzi

**Comment by reespozzi** [comment]
Could you test with local to see which are actually needed? @NickAzureDevops

**Comment by NickAzureDevops** [comment]
> Could you test with local to see which are actually needed? @NickAzureDevops

Those are installed when I run it locally.  it working so it is good

**Review by reespozzi — APPROVED** [review]

**Pull request merged**
